events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 100M;

    server {
        listen 80;
        server_name localhost; # Troque pelo seu domínio no futuro

        # Django Static (Comentado em modo DEV para auto-reload funcionar)
        # location /static/ {
        #     alias /var/www/static/;
        # }

        # Django Media
        location /media/ {
            alias /var/www/media/;
        }

        # GeoServer
        location /geoserver/ {
            proxy_pass http://geoserver:8080/geoserver/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 300;
        }

        # Django App
        location / {
            proxy_pass http://django:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}