# Generated by Django 4.2.9 on 2026-02-22 21:52

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDETER',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('data_alerta', models.DateField()),
                ('classe', models.CharField(max_length=50)),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('satelite', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Alerta DETER',
                'verbose_name_plural': 'Alertas DETER',
                'db_table': 'geo"."alertas_deter',
                'ordering': ['-data_alerta'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaProtegida',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('esfera', models.CharField(blank=True, max_length=50, null=True)),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('ato_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('ano_criacao', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Área Protegida',
                'verbose_name_plural': 'Áreas Protegidas',
                'db_table': 'geo"."areas_protegidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BairroPVH',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('area_km2', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('populacao', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Bairro de Porto Velho',
                'verbose_name_plural': 'Bairros de Porto Velho',
                'db_table': 'geo"."bairros_pvh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesmatamentoPVH',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('data_deteccao', models.DateField(null=True)),
                ('fonte', models.CharField(default='PRODES/INPE', max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Desmatamento PVH',
                'verbose_name_plural': 'Desmatamentos PVH',
                'db_table': 'geo"."desmatamento_pvh',
                'ordering': ['-ano'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FocoCalor',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField()),
                ('satelite', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura_k', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('frp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Foco de Calor',
                'verbose_name_plural': 'Focos de Calor',
                'db_table': 'geo"."focos_calor',
                'ordering': ['-data_hora'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MunicipioRO',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('cod_ibge', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(default='RO', max_length=2)),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('populacao', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Município de RO',
                'verbose_name_plural': 'Municípios de RO',
                'db_table': 'geo"."municipios_ro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ/Registro')),
                ('historico', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Histórico do Ator')),
                ('dados_sensiveis', models.BooleanField(default=False, verbose_name='Dados Sensíveis')),
            ],
            options={
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Bioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Bioma')),
            ],
        ),
        migrations.CreateModel(
            name='Conflito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Caso')),
                ('resumo', models.TextField(verbose_name='Resumo Curto')),
                ('historico_completo', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Histórico Detalhado')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DireitoAfetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Direito Afetado')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='DistritoPVH',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('populacao_2022', models.CharField(blank=True, max_length=50, null=True)),
                ('distancia_sede', models.CharField(blank=True, max_length=50, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Distrito de Porto Velho',
                'verbose_name_plural': 'Distritos de Porto Velho',
                'db_table': 'geo"."distritos_pvh',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FaseConflito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Fase do Conflito')),
            ],
        ),
        migrations.CreateModel(
            name='LimitePVH',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='Porto Velho', max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Limite de Porto Velho',
                'verbose_name_plural': 'Limites de Porto Velho',
                'db_table': 'geo"."limite_pvh',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PapelAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Papel do Ator')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('corpo_texto', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo')),
                ('data_fato', models.DateField(blank=True, null=True, verbose_name='Data do Fato')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Publicação')),
                ('fonte_original', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonte')),
                ('anexo_pdf', models.FileField(blank=True, null=True, upload_to='publicacoes/anexos/', verbose_name='Anexo (PDF)')),
                ('is_publicado', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('is_restrito', models.BooleanField(default=False, verbose_name='Restrito?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atores_citados', models.ManyToManyField(blank=True, to='core_gis.ator')),
                ('conflito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes', to='core_gis.conflito')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='SecaoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('tipo', models.CharField(choices=[('publicacao', 'Publicação'), ('dashboard', 'Dashboard'), ('mapa', 'Mapa Interativo')], default='publicacao', max_length=20, verbose_name='Tipo da Seção')),
                ('icone', models.CharField(help_text="Nome do arquivo SVG do ícone (ex: 'chart-line.svg')", max_length=100, verbose_name='Ícone (SVG)')),
                ('cor_fundo', models.CharField(default='var(--theme-bg-white)', help_text='Cor ou variável CSS de fundo da seção', max_length=100, verbose_name='Variável de Cor do Fundo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('url', models.CharField(default='#', help_text="URL ou nome da rota (ex: 'core_gis:lista_mapas')", max_length=255, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Seção da Home',
                'verbose_name_plural': 'Seções da Home',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='SetorCensitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_setor', models.CharField(max_length=15, unique=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('nm_regiao', models.CharField(blank=True, max_length=50, null=True)),
                ('area_km2', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4674)),
            ],
            options={
                'db_table': '"geo"."core_gis_setorcensitario"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SetorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Setor Econômico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Ator')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Documento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTerritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Território')),
            ],
        ),
        migrations.CreateModel(
            name='TipoViolacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Tipo de Violação')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacaoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='publicacoes/imagens/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição. A primeira (menor número) será a capa da publicação.', verbose_name='Ordem')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core_gis.publicacao')),
            ],
            options={
                'verbose_name': 'Imagem da Publicação',
                'verbose_name_plural': 'Imagens da Publicação',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='publicacao',
            name='tipo_documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.tipodocumento'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='violacoes_denunciadas',
            field=models.ManyToManyField(blank=True, to='core_gis.tipoviolacao'),
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_territorio', models.CharField(max_length=200, verbose_name='Nome do Território')),
                ('municipio', models.CharField(max_length=150, verbose_name='Município')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.bioma')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.tipoterritorio')),
            ],
        ),
        migrations.AddField(
            model_name='conflito',
            name='direitos_afetados',
            field=models.ManyToManyField(blank=True, to='core_gis.direitoafetado'),
        ),
        migrations.AddField(
            model_name='conflito',
            name='fase_atual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.faseconflito'),
        ),
        migrations.AddField(
            model_name='conflito',
            name='localizacoes',
            field=models.ManyToManyField(related_name='conflitos', to='core_gis.localizacao'),
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ex: sobre, mensagem_inicio, rodape_informativo', max_length=100, unique=True, verbose_name='Identificador')),
                ('corpo_texto', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.CreateModel(
            name='CardSecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Card')),
                ('subtitulo', models.TextField(blank=True, null=True, verbose_name='Subtítulo/Descrição')),
                ('url', models.CharField(help_text="URL ou nome da rota (ex: 'core_gis:lista_mapas')", max_length=255, verbose_name='URL')),
                ('icone', models.CharField(help_text='Nome do arquivo SVG do ícone da badge', max_length=100, verbose_name='Ícone (SVG)')),
                ('texto_botao', models.CharField(default='Acessar', max_length=100, verbose_name='Texto do Botão')),
                ('btn_class', models.CharField(default='btn-primary', help_text='ex: btn-primary', max_length=50, verbose_name='Classe CSS do Botão')),
                ('badge_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto da Badge')),
                ('badge_class', models.CharField(blank=True, help_text='ex: theme-forest', max_length=50, null=True, verbose_name='Classe CSS da Badge')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core_gis.secaohome', verbose_name='Seção')),
            ],
            options={
                'verbose_name': 'Card da Seção',
                'verbose_name_plural': 'Cards da Seção',
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='ator',
            name='setor_economico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.setoreconomico'),
        ),
        migrations.AddField(
            model_name='ator',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.tipoator'),
        ),
        migrations.CreateModel(
            name='EnvolvimentoAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_gis.ator')),
                ('conflito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_gis.conflito')),
                ('papel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.papelator')),
            ],
            options={
                'verbose_name': 'Envolvimento de Ator',
                'verbose_name_plural': 'Envolvimentos de Atores',
                'unique_together': {('conflito', 'ator', 'papel')},
            },
        ),
    ]
