# Generated by Django 4.2.9 on 2026-02-07 21:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDETER',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('data_alerta', models.DateField()),
                ('classe', models.CharField(max_length=50)),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('satelite', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Alerta DETER',
                'verbose_name_plural': 'Alertas DETER',
                'db_table': 'geo"."alertas_deter',
                'ordering': ['-data_alerta'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaProtegida',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('esfera', models.CharField(blank=True, max_length=50, null=True)),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=14, null=True)),
                ('ato_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('ano_criacao', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Área Protegida',
                'verbose_name_plural': 'Áreas Protegidas',
                'db_table': 'geo"."areas_protegidas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BairroPVH',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('area_km2', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('populacao', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Bairro de Porto Velho',
                'verbose_name_plural': 'Bairros de Porto Velho',
                'db_table': 'geo"."bairros_pvh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesmatamentoPVH',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('data_deteccao', models.DateField(null=True)),
                ('fonte', models.CharField(default='PRODES/INPE', max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Desmatamento PVH',
                'verbose_name_plural': 'Desmatamentos PVH',
                'db_table': 'geo"."desmatamento_pvh',
                'ordering': ['-ano'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FocoCalor',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField()),
                ('satelite', models.CharField(blank=True, max_length=50, null=True)),
                ('temperatura_k', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('frp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Foco de Calor',
                'verbose_name_plural': 'Focos de Calor',
                'db_table': 'geo"."focos_calor',
                'ordering': ['-data_hora'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MunicipioRO',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('cod_ibge', models.CharField(blank=True, max_length=10, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('uf', models.CharField(default='RO', max_length=2)),
                ('area_km2', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('populacao', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Município de RO',
                'verbose_name_plural': 'Municípios de RO',
                'db_table': 'geo"."municipios_ro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistritoPVH',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('populacao_2022', models.CharField(blank=True, max_length=50, null=True)),
                ('distancia_sede', models.CharField(blank=True, max_length=50, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Distrito de Porto Velho',
                'verbose_name_plural': 'Distritos de Porto Velho',
                'db_table': 'geo"."distritos_pvh',
                'managed': True,
            },
        ),
    ]
