# Generated by Django 4.2.9 on 2026-02-07 23:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_gis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitePVH',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='Porto Velho', max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Limite de Porto Velho',
                'verbose_name_plural': 'Limites de Porto Velho',
                'db_table': 'geo"."limite_pvh',
                'managed': True,
            },
        ),
    ]
