# Generated by Django 4.2.9 on 2026-02-23 01:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_gis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distritopvh',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
