# Generated by Django 4.2.9 on 2026-03-17 00:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_gis', '0002_alter_distritopvh_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coluna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_css', models.CharField(choices=[('col-12', 'Largura Total (100%)'), ('col-lg-8', 'Larga (66%)'), ('col-lg-6', 'Metade (50%)'), ('col-lg-4', 'Estreita (33%)'), ('col-lg-3', 'Muito Estreita (25%)')], default='col-lg-6', max_length=20, verbose_name='Tamanho da Coluna')),
                ('tipo_conteudo', models.CharField(choices=[('quadros', 'Lista de Quadros (Stat Cards)'), ('tabela', 'Tabela de Dados'), ('grafico', 'Gráfico')], max_length=20, verbose_name='Tipo de Conteúdo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem na Linha')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='DashboardDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Dashboard')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('tema_class', models.CharField(default='theme-default', help_text='Ex: theme-deter, theme-prodes', max_length=50, verbose_name='Tema CSS')),
                ('icone_header', models.CharField(default='bi-graph-up', max_length=50, verbose_name='Ícone do Cabeçalho')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaDinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Tabela')),
                ('icone', models.CharField(default='bi-table', max_length=50, verbose_name='Ícone')),
                ('arquivo_csv', models.FileField(blank=True, null=True, upload_to='dashboards/csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='Importar CSV')),
                ('cabecalhos', models.JSONField(blank=True, default=list, verbose_name='Cabeçalhos da Tabela')),
                ('linhas_dados', models.JSONField(blank=True, default=list, verbose_name='Dados das Linhas')),
                ('coluna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tabela', to='core_gis.coluna')),
            ],
        ),
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título/Label')),
                ('valor', models.CharField(max_length=50, verbose_name='Valor (Número ou Texto)')),
                ('icone', models.CharField(default='bi-bar-chart', max_length=50, verbose_name='Ícone (Bootstrap Icons)')),
                ('icone_cor', models.CharField(default='text-primary', help_text='Ex: text-danger, text-success', max_length=50, verbose_name='Cor do Ícone (Classe CSS)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadros', to='core_gis.coluna')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='core_gis.dashboarddinamico')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='GraficoDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Gráfico')),
                ('tipo', models.CharField(choices=[('bar', 'Gráfico de Barras (Bar)'), ('line', 'Gráfico de Linhas (Line)'), ('pie', 'Gráfico de Pizza (Pie)'), ('doughnut', 'Gráfico de Rosca (Doughnut)')], default='bar', max_length=20, verbose_name='Tipo do Gráfico')),
                ('arquivo_csv', models.FileField(blank=True, null=True, upload_to='dashboards/csv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='Importar Dados via CSV')),
                ('labels', models.JSONField(blank=True, default=list, verbose_name='Rótulos (Eixo X)')),
                ('datasets', models.JSONField(blank=True, default=list, verbose_name='Conjunto de Dados')),
                ('coluna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grafico', to='core_gis.coluna')),
            ],
        ),
        migrations.AddField(
            model_name='coluna',
            name='linha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='core_gis.linha'),
        ),
    ]
