# Generated by Django 4.2.9 on 2026-02-18 15:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_gis', '0002_limitepvh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ/Registro')),
                ('historico', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Histórico do Ator')),
                ('dados_sensiveis', models.BooleanField(default=False, verbose_name='Dados Sensíveis')),
            ],
            options={
                'verbose_name_plural': 'Atores',
            },
        ),
        migrations.CreateModel(
            name='Bioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Bioma')),
            ],
        ),
        migrations.CreateModel(
            name='Conflito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Caso')),
                ('resumo', models.TextField(verbose_name='Resumo Curto')),
                ('historico_completo', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Histórico Detalhado')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DireitoAfetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Direito Afetado')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='FaseConflito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Fase do Conflito')),
            ],
        ),
        migrations.CreateModel(
            name='PapelAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Papel do Ator')),
            ],
        ),

        migrations.CreateModel(
            name='SetorEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Setor Econômico')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Ator')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Documento')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTerritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Tipo de Território')),
            ],
        ),
        migrations.CreateModel(
            name='TipoViolacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Tipo de Violação')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('corpo_texto', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo')),
                ('data_fato', models.DateField(blank=True, null=True, verbose_name='Data do Fato')),
                ('data_publicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Publicação')),
                ('fonte_original', models.CharField(blank=True, max_length=150, null=True, verbose_name='Fonte')),
                ('anexo_pdf', models.FileField(blank=True, null=True, upload_to='publicacoes/anexos/', verbose_name='Anexo (PDF)')),
                ('is_publicado', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('is_restrito', models.BooleanField(default=False, verbose_name='Restrito?')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atores_citados', models.ManyToManyField(blank=True, to='core_gis.ator')),
                ('conflito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes', to='core_gis.conflito')),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.tipodocumento')),
                ('violacoes_denunciadas', models.ManyToManyField(blank=True, to='core_gis.tipoviolacao')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_territorio', models.CharField(max_length=200, verbose_name='Nome do Território')),
                ('municipio', models.CharField(max_length=150, verbose_name='Município')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bioma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.bioma')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.tipoterritorio')),
            ],
        ),
        migrations.AddField(
            model_name='conflito',
            name='direitos_afetados',
            field=models.ManyToManyField(blank=True, to='core_gis.direitoafetado'),
        ),
        migrations.AddField(
            model_name='conflito',
            name='fase_atual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.faseconflito'),
        ),
        migrations.AddField(
            model_name='conflito',
            name='localizacoes',
            field=models.ManyToManyField(related_name='conflitos', to='core_gis.localizacao'),
        ),
        migrations.AddField(
            model_name='ator',
            name='setor_economico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.setoreconomico'),
        ),
        migrations.AddField(
            model_name='ator',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.tipoator'),
        ),
        migrations.CreateModel(
            name='EnvolvimentoAtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_gis.ator')),
                ('conflito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_gis.conflito')),
                ('papel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_gis.papelator')),
            ],
            options={
                'verbose_name': 'Envolvimento de Ator',
                'verbose_name_plural': 'Envolvimentos de Atores',
                'unique_together': {('conflito', 'ator', 'papel')},
            },
        ),
    ]
