# Generated by Django 4.2.9 on 2026-02-22 15:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_gis', '0003_ator_bioma_conflito_direitoafetado_faseconflito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicacaoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='publicacoes/imagens/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição. A primeira (menor número) será a capa da publicação.', verbose_name='Ordem')),
                ('legenda', models.CharField(blank=True, max_length=255, null=True, verbose_name='Legenda')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='core_gis.publicacao')),
            ],
            options={
                'verbose_name': 'Imagem da Publicação',
                'verbose_name_plural': 'Imagens da Publicação',
                'ordering': ['ordem'],
            },
        ),
    ]
