# Generated by Django 4.2.9 on 2026-02-22 18:25

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_gis', '0004_setorcensitario_publicacaoimagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorCensitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_setor', models.CharField(max_length=15, unique=True)),
                ('situacao', models.CharField(blank=True, max_length=50, null=True)),
                ('nm_regiao', models.CharField(blank=True, max_length=50, null=True)),
                ('area_km2', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4674)),
            ],
            options={
                'db_table': '"geo"."core_gis_setorcensitario"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Ex: sobre, mensagem_inicio, rodape_informativo', max_length=100, unique=True, verbose_name='Identificador')),
                ('corpo_texto', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data de Alteração')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
